# Generated by Django 4.0.2 on 2022-02-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModelCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('key_partners', models.TextField(blank=True, default='')),
                ('key_activies', models.TextField(blank=True, default='')),
                ('key_resources', models.TextField(blank=True, default='')),
                ('value_propositions', models.TextField(blank=True, default='')),
                ('customer_relationships', models.TextField(blank=True, default='')),
                ('channels', models.TextField(blank=True, default='')),
                ('customer_segments', models.TextField(blank=True, default='')),
                ('cost_structure', models.TextField(blank=True, default='')),
                ('revenue_streams', models.TextField(blank=True, default='')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_model_canvas.businessmodelcanvas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
