# Generated by Django 4.0.2 on 2022-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_model_canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodelcanvas',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
