# Generated by Django 4.0 on 2022-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_model_canvas', '0002_businessmodelcanvas_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodelcanvas',
            name='one_sentence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
