# Generated by Django 4.0.2 on 2022-02-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_model_canvas', '0004_alter_businessmodelcanvas_options_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
