# Generated by Django 4.0.2 on 2022-02-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='integrated_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='one_line_character',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='one_line_free',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='one_line_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='one_line_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='one_line_success',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_are_they_feeling_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_are_they_feeling_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_do_they_have_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_do_they_have_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_is_an_average_day_like_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_is_an_average_day_like_to',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_is_their_status_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='what_is_their_status_to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
